MONGO_URI = "mongodb://localhost:27017/wad"
SECRET_KEY = "a3a5f8968bd0d4aa03b3d644232e7349" #Generated by: secrets.token_hex(16)
UPLOAD_FOLDER = "./static/upload"
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}
GITHUB_PROFILE_PAGE_URL = 'https://www.github.com/'
NUMBER_OF_SHOWN_POSTS = 50